---
- name: Test Playbook
  hosts: localhost
  gather_facts: true
  collections:
    - devsec.hardening
  tasks:
    - import_role:
        name: os_hardening

    - debug:
        msg:
          "testing"
